CREATE TABLE IF NOT EXISTS UTILISATEUR (
  Id_Utilisateur INT PRIMARY KEY,
  Email VARCHAR(255) UNIQUE NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Nom VARCHAR(255) NOT NULL,
  Prenom VARCHAR(255) NOT NULL,
  Date_creation DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS PROPRIETAIRE_PARKING (
  Id_Proprietaire INT PRIMARY KEY,
  Email VARCHAR(255) UNIQUE NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Nom VARCHAR(255) NOT NULL,
  Prenom VARCHAR(255) NOT NULL,
  Date_creation DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS PARKING (
  Id_Parking INT PRIMARY KEY,
  Id_Proprietaire INT NOT NULL REFERENCES PROPRIETAIRE_PARKING(Id_Proprietaire),
  Nom VARCHAR(255) NOT NULL,
  Adresse VARCHAR(255) NOT NULL,
  Latitude DECIMAL(10, 8) NOT NULL,
  Longitude DECIMAL(11, 8) NOT NULL,
  Capacite_total INT NOT NULL,
  Ouvert_24_7 BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS TYPE_ABONNEMENT (
  Id_Type INT PRIMARY KEY,
  Nom VARCHAR(255) NOT NULL,
  Description TEXT NULL
);

CREATE TABLE IF NOT EXISTS ABONNEMENT (
  Id_Abonnement INT PRIMARY KEY,
  Id_Utilisateur INT NOT NULL REFERENCES UTILISATEUR(Id_Utilisateur),
  Id_Parking INT NOT NULL REFERENCES PARKING(Id_Parking),
  Id_Type INT NOT NULL REFERENCES TYPE_ABONNEMENT(Id_Type),
  Date_debut DATE NOT NULL,
  Date_fin DATE NOT NULL,
  Prix_mensuel DECIMAL(10, 2) NOT NULL,
  Statut VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CRENEAU_ABONNEMENT (
  Id_Creneau INT PRIMARY KEY,
  Id_Type INT NOT NULL REFERENCES TYPE_ABONNEMENT(Id_Type),
  Jour_semaine_debut TINYINT NOT NULL,
  Heure_debut TIME NOT NULL,
  Jour_semaine_fin TINYINT NOT NULL,
  Heure_fin TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS RESERVATION (
  Id_Reservation INT PRIMARY KEY,
  Id_Utilisateur INT NOT NULL REFERENCES UTILISATEUR(Id_Utilisateur),
  Id_Parking INT NOT NULL REFERENCES PARKING(Id_Parking),
  Date_heure_debut DATETIME NOT NULL,
  Date_heure_fin DATETIME NOT NULL,
  Statut VARCHAR(50) NOT NULL,
  Montant_calcule DECIMAL(10, 2) NOT NULL,
  Montant_final DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS STATIONNEMENT (
  Id_Stationnement INT PRIMARY KEY,
  Id_Utilisateur INT NOT NULL REFERENCES UTILISATEUR(Id_Utilisateur),
  Id_Parking INT NOT NULL REFERENCES PARKING(Id_Parking),
  Id_Reservation INT NULL REFERENCES RESERVATION(Id_Reservation),
  Date_heure_entree DATETIME NOT NULL,
  Date_heure_sortie DATETIME NULL,
  Montant_final DECIMAL(10, 2) NULL,
  Penalite_appliquee BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS REGLE_TARIFAIRE (
  Id_Regle INT PRIMARY KEY,
  Id_Parking INT NOT NULL REFERENCES PARKING(Id_Parking),
  Duree_debut_minute INT NOT NULL,
  Duree_fin_minute INT NULL,
  Prix_par_tranche DECIMAL(10, 2) NOT NULL,
  Tranche_minute INT DEFAULT 15 NOT NULL,
  Date_application DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS HORAIRE_OUVERTURE (
  Id_Horaire INT PRIMARY KEY,
  Id_Parking INT NOT NULL REFERENCES PARKING(Id_Parking),
  Jour_semaine TINYINT NOT NULL,
  Heure_ouverture TIME NOT NULL,
  Heure_fermeture TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS FACTURE (
  Id_Facture INT PRIMARY KEY,
  Id_Reservation INT NULL REFERENCES RESERVATION(Id_Reservation),
  Id_Stationnement INT NULL REFERENCES STATIONNEMENT(Id_Stationnement),
  Date_emission DATETIME NOT NULL,
  Montant_HT DECIMAL(10, 2) NOT NULL,
  Montant_TTC DECIMAL(10, 2) NOT NULL,
  Detail_json TEXT NULL,
  Type_facture VARCHAR(50) NOT NULL
);